AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # for ResNet50V2 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.001
REGISTERED_MODEL_NAME: ResNet50V2Model
