artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Dlpv8DOCmloKTiqwx-pPJASAlu3g8vhV/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  dataset_name: Cars-Tanks-Dataset



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras



evaluation:
  root_dir: artifacts/evaluation
  model_path: artifacts/training/model.keras
  dataset_dir: artifacts/data_ingestion/Cars-Tanks-Dataset
  metric_file_name: artifacts/evaluation/metrics.json
  confusion_matrix_file_path: artifacts/evaluation/confusion_matrix.png
  confusion_matrix_data_file_path: artifacts/evaluation/confusion_matrix.json
  roc_curve_file_path: artifacts/evaluation/roc_curve.png
  roc_data_file_path: artifacts/evaluation/roc_data.json
